export const LOAD_PRIV_KEY = "LOAD_PRIV_KEY";
export const LOAD_ADDRESS = "LOAD_ADDRESS";
export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";
export const SET_RECIPIENT = "SET_RECIPIENT";
export const SET_ACCOUNT_BALANCE = "SET_ACCOUNT_BALANCE";
export const CHECK_FOR_USER = "CHECK_FOR_USER";
export const RECEIVE_NICKNAME = "RECEIVE_NICKNAME";
